project_id = "rdyqyaacfkopruprxkpq"

[functions.geolocate]
verify_jwt = false

[functions.track-page-view]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
